name: Build CLI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  publish-cli:
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - { name: win_x64, os: windows-latest, runtime: win-x64, executable: AssetRipper.CLI.Free.exe, archive: zip }
          - { name: win_arm64, os: windows-latest, runtime: win-arm64, executable: AssetRipper.CLI.Free.exe, archive: zip }
          - { name: linux_x64, os: ubuntu-22.04, runtime: linux-x64, executable: AssetRipper.CLI.Free, archive: tar }
          - { name: linux_arm64, os: ubuntu-22.04-arm, runtime: linux-arm64, executable: AssetRipper.CLI.Free, archive: tar }
          - { name: mac_x64, os: macos-14, runtime: osx-x64, executable: AssetRipper.CLI.Free, archive: tar }
          - { name: mac_arm64, os: macos-14, runtime: osx-arm64, executable: AssetRipper.CLI.Free, archive: tar }

    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Publish CLI
        run: dotnet publish -c Release -r ${{ matrix.config.runtime }}
        working-directory: ./Source/AssetRipper.CLI.Free/

      - name: Timestamp compilation
        shell: bash
        run: date -u > ./Source/AssetRipper.CLI.Free/bin/Release/${{ matrix.config.runtime }}/publish/compile_time.txt

      - name: Archive & Upload (zip)
        if: ${{ matrix.config.archive == 'zip' }}
        uses: actions/upload-artifact@v7
        with:
          name: AssetRipper_CLI_${{ matrix.config.name }}
          path: |
            ./Source/AssetRipper.CLI.Free/bin/Release/${{ matrix.config.runtime }}/publish/${{ matrix.config.executable }}
            ./Source/AssetRipper.CLI.Free/bin/Release/${{ matrix.config.runtime }}/publish/*.dll
            ./Source/AssetRipper.CLI.Free/bin/Release/${{ matrix.config.runtime }}/publish/*.so
            ./Source/AssetRipper.CLI.Free/bin/Release/${{ matrix.config.runtime }}/publish/*.dylib
            ./Source/AssetRipper.CLI.Free/bin/Release/${{ matrix.config.runtime }}/publish/compile_time.txt
          if-no-files-found: error

      - name: Create Archive (tar)
        if: ${{ matrix.config.archive == 'tar' }}
        shell: bash
        working-directory: ./Source/AssetRipper.CLI.Free/bin/Release/${{ matrix.config.runtime }}/publish
        run: tar cvJf "AssetRipper_CLI_${{ matrix.config.name }}.tar.xz" "${{ matrix.config.executable }}" compile_time.txt $(ls *.{dll,so,dylib} 2>/dev/null)

      - name: Upload Archive (tar)
        if: ${{ matrix.config.archive == 'tar' }}
        uses: actions/upload-artifact@v7
        with:
          name: AssetRipper_CLI_${{ matrix.config.name }}
          path: ./Source/AssetRipper.CLI.Free/bin/Release/${{ matrix.config.runtime }}/publish/AssetRipper_CLI_${{ matrix.config.name }}.tar.xz
